### ISSUE TITLE
اشتباهی درباره‌ی «ایران‌اپس» وجود داره

### ISSUE THREAD

**Issue by SalehNiknejad** [IKAcc/Nakamology#28]
**چه چیزی درباره‌ی این پروژه اشتباه بوده؟**

منابع این مورد درباره پلتفرم 2نیت هست (دونیت)

با تشکر از وبسایت خوبتون

**Comment by Javid-Izadfar** [comment]
ممنونم بابت اطلاع رسانی. تصحیح شد
