### ISSUE TITLE
چه بلایی سرش اومده

### ISSUE THREAD

**Issue by mrfelfel** [IKAcc/Nakamology#3]
سلام ناکامولوژی چیشده ؟‌

**Comment by mrfelfel** [comment]
با اجازه من ریبوتش میکنم / تحت یک فورک جدید

**Comment by Javid-Izadfar** [comment]
@mrfelfel سلام دوست عزیز
نسخه‌ی جدید پروژه بالا اومده. 
شرمنده که اینقدر طول کشید
