### ISSUE TITLE
اشتباهی درباره‌ی «آی‌هوم» وجود داره

### ISSUE THREAD

**Issue by MahdiRahmani80** [IKAcc/Nakamology#32]
**چه چیزی درباره‌ی این پروژه اشتباه بوده؟**
لینک https://ihome.ir دیگه وجود نداره و اون رو وارد صفحه خرید دامنه میکنه، پیشنهادم این هست که از حالت لینک برش دارید. 
به نظرم یه ایده خوب این هست که url سایت های قدیمی رو هم اضافه کنید تا اگه کسی خواست بیشتر بچرخه تو جا های مختلف یا اگه کسی خواست که همون راه رو ادامه بده یا هر چی دسترسی داشته باشه (منظورم تو همون بخش اطلاعات کلی)
**یک یا چند منبع برای این اطلاعات**
صرفا چند نظر شخصی بود

**Comment by Javid-Izadfar** [comment]
متشکرم بابت گزارش. فیکس شد.

در مورد آدرس اصلی سایت هم فکر خوبیه. اگه میتونید، زحمتشو بکشید.

**Comment by Javid-Izadfar** [comment]
من این ایشو رو میبندم. در صورتی که مایل بودید، برای «اضافه کردن آدرس سایت» یه ایشوی دیگه باز کنید

**Comment by MahdiRahmani80** [comment]
خیلی ممنونم آقا جاوید
من تخصص زیادی در زمینه وب ندارم، بیشتر برنامه نویس اندروید هستم.
راستی از آشنایی با شما هم بسیار خوشوقتم :)
