### ISSUE TITLE
اشتباهی درباره‌ی «چیلیوری» وجود داره

### ISSUE THREAD

**Issue by MahdiRahmani80** [IKAcc/Nakamology#33]
**چه چیزی درباره‌ی این پروژه اشتباه بوده؟**
توی این قسمت، برچسب حمل و نقل، اشتباه تایپی دارد. و حل و نقل نوشته شده
**یک یا چند منبع برای این اطلاعات**

**Comment by Javid-Izadfar** [comment]
ممنونم بابت گزارش. فیکس شد
