### ISSUE TITLE
اشتباهی درباره‌ی «ایران‌فیلم» وجود داره

### ISSUE THREAD

**Issue by YMZnew** [IKAcc/Nakamology#35]
**چه چیزی درباره‌ی این پروژه اشتباه بوده؟**
ایران فیلم از سال ۹۱ فیلتر بود و فقط با تغییر دامنه کار میکرد. تا سالهای سال هم همین مدل بود. بعد ها تغییر دامنه رو کلا متوقف کرد و دیگه مرجع دانلود فیلم هم نبود. صرفا یه بانک خیلی خوب از مشخصات  فیلم ها بود که میشد سرچ زد و فیلم های مورد نظرمونو پیدا کرد( فیلتر دسته بندی خیلی خوبی داشت) و گاهی تو مشخصات فیلم، برای دانلود به سایت های دیگه ارجاع میداد.
دلیلی که نوشتید هم تاریخش درست نیست هم دلیل توقف ایران فیلم نیست. 
ضمن اینکه همین الان سایت های فیلم زیادی هستند که سالهاس دارن با تغییر دامنه کار میکنن.
و همین طور این موضوع که از حدود ۱۴۰۰ نوع کاربری ایران فیلم از دانلود فیلم ، به بانک جستجوی فیلم تغییر پیدا کرده بود. 

**یک یا چند منبع برای این اطلاعات**

**Comment by Javid-Izadfar** [comment]
این اطلاعات بر اساس[ توییت‌های حمید تیموری](https://twitter.com/HamidTeimouriii/status/1614892679694848000) نوشته شدن.
اگر جایی رو میشناسید که خلاف این موضوع صحبت کرده باشه، ممنون میشم به اشتراک بزارید
