### ISSUE TITLE
اشتباهی درباره‌ی «پیمنت ۲۴» وجود داره

### ISSUE THREAD

**Issue by La-Volpe** [IKAcc/Nakamology#36]
**چه چیزی درباره‌ی این پروژه اشتباه بوده؟**

[منبع](https://iranwire.com/fa/features/38421/)

در واقع به دلیل عملیات OFAC بابت دور زدن تحریم ها و همینطور اتهام فاندر اصلیش یعنی سجاد «سهیل» شهیدیان بسته شد.

**Comment by Javid-Izadfar** [comment]
ممنونم.

اعمال شد
https://github.com/IKAcc/Nakamology/commit/24a2521bdc3af9d533e9aa8295c59855a65c4a94
