### ISSUE TITLE
اشتباهی درباره‌ی «ریحون» وجود داره

### ISSUE THREAD

**Issue by mgharahi** [IKAcc/Nakamology#38]
**چه چیزی درباره‌ی این پروژه اشتباه بوده؟**

قسمت دلیل ناکامی-> پاراگراف دوم -> بیزینس های مشابه که شکست خوردند یکیش خود ریحون اشاره شده. به نظر باید به چلیوری لینک میشد

**Comment by Javid-Izadfar** [comment]
ممنونم بابت اطلاع‌رسانی. فیکس شد
