### ISSUE TITLE
شرکت بهزی

### ISSUE THREAD

**Issue by hekmatinasser** [IKAcc/Nakamology#41]
استارت اپی که برای رابط بین بیماران و دکتر ها طراحی شده بود و قبل اپلیکشن های مشابه وارد بازار شد و تو دوره اوج کرونا هم دیده شد. 

ابتدا شرکت سرمایه گذار رهیاب گستر بود اما بزینس پلن ضعیف باعث شده سرمایه گذار عوض بشه و سرمایه گذار جدید که سایت فروش انلاین دارو به نام بهتیام داشت افرادش با مجموعه بهزی ادغام شدند. بیشتر از یک سال به این اپلیکشن و فروشگاه نگذشت که سرمایه گذار  هم تصمیم به تعطیلی در شهریور 1401 گرفت 

دلایلی چون دخالت مستقیم مدیر عامل در امور کارشناسان
 جابجایی بیش ازحد فضای کاری
 رنج حقوقی پایین کارمندان 
 تصمیمات خلق الساعه مدیر عامل

خودم کارمند این شرکت بودم که اسفند 1401 جدا شدم

**Comment by Javid-Izadfar** [comment]
دوست عزیز سلام

متاسفانه من جز این چندلینک، محتوای دیگه‌ای در مورد بهزی پیدا نکردم.

https://ecosystem.ir/legal/3921/
https://digiato.com/article/2020/04/18/%D9%86%DA%AF%D8%A7%D9%87%DB%8C-%D8%A8%D9%87-%D8%B9%D9%85%D9%84%DA%A9%D8%B1%D8%AF-%D8%A7%D8%B3%D8%AA%D8%A7%D8%B1%D8%AA%D8%A7%D9%BE%E2%80%8C%D9%87%D8%A7%DB%8C-%D9%85%D9%88%D8%B1%D8%AF-%D8%AD%D9%85%D8%A7

میتونید منبع‌هایی رو برای صحبتتون معرفی کنید؟

**Comment by hekmatinasser** [comment]
سایت جابینجا مشاهده کنید همه اگهی ها منقضی شده و  همه افراد تیم  تعدیل شدند
