### ISSUE TITLE
نمایش اشتباه تاریخ پایان پروژه

### ISSUE THREAD

**Issue by ranarouz** [IKAcc/Nakamology#6]
**Describe the bug**
در صفحه تمام پروژه ها تاریخ پایان پروژه به اشتباه همان تاریخ شروع پروژه درج شده است

**To Reproduce**
1. به طور مثال در صفحه «لیست ناکامی ها» برای هر پروژه یک بازه زمانی شروع و پایان مشخص شده است 
2. روی پروژه ای کلیک کنید
3. در صفحه جدید مشاهده میکنید که تاریخ پایان اشتباه درج شده است

**Desktop:**
 - OS: Windows 7
 - Browser: chrome
 - Version :  91.0.4472.106

**Comment by Javid-Izadfar** [comment]
با تشکر از @saeedesmaili، توی این [مرج ریکوئست](https://github.com/IKAcc/Nakamology/pull/5) حل شده
